CREATE USER 'dt_user'@'%' identified by 'password';
GRANT USAGE ON *.* TO 'dt_user'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `dt_db`.* TO 'dt_user'@'%';